# GUI Design for System
GUI window includes circular gauge depicting the voltage generated by Generator (DC Motor) in milliVolts(mV).

This design is based on example provided by Marko Mattila, marko.a.mattila@gmail.com (https://github.com/zchydem/qt-examples/tree/master/gauge-example).

